version: '3'

services:
  api: 
    build:
      context: .
      dockerfile: portal.Dockerfile

  frontend:
    build:
      context: .
      dockerfile: dashboard.Dockerfile

  db-backup:
    build:
      context: ./docker/backup
      dockerfile: Dockerfile