jwt:
  secret: 'example@123'

app:
  runchainhook: false
  runjobs: false
  fluentdlogging: false
  runthrottle: false

db:
  host: 'localhost'
  type: 'postgres'
  port: 5432
  username: 'root'
  password: 'secret'
  synchronize: false
  database: api

queue:
  driver: 'redis'
  host: 'localhost'
  port: 6379
  db: ''
  password: ''
  username: ''

throttle:
  enabled: false
  global:
    ttl: 60
    limit: 60
  login:
    prefix: 'login_fail_throttle'
    limit: 5
    duration: 2592000
    blockDuration: 3000
