jwt:
  secret: 'example@123'

app:
  runchainhook: false
  runjobs: false
  fluentdlogging: false

db:
  host: 'localhost'
  type: 'postgres'
  port: 5432
  username: 'root'
  password: 'secret'
  synchronize: false
  database: api
