{
 "title": "RabbitMQ Dashboard",
 "tags": [ "rabbitmq" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Number of Queues",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rabbitmq_queues_total" }
   ]
  },
  {
   "title": "Total Number of Exchanges",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "rabbitmq_exchanges_total" }
   ]
  },
  {
   "title": "Messages Published Rate (per second)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(rabbitmq_channel_messages_published_total[1m])"
    }
   ]
  },
  {
   "title": "Messages Delivered Rate (per second)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "rate(rabbitmq_queue_messages_delivered_total[1m])"
    }
   ]
  },
  {
   "title": "Messages in Queues",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_queue_messages" }
   ]
  },
  {
   "title": "Memory usage (bytes)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "targets": [
    { "expr": "rabbitmq_node_mem_used_bytes" }
   ]
  },
  {
   "title": "Free Disk Space (bytes)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    { "expr": "rabbitmq_node_disk_free_bytes" }
   ]
  }
 ]
}