name: Deps - Build and Push

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

    - name: Build images with Docker Compose
      run: docker-compose -f docker-compose.deps.ci.yml build

    - name: Tag and Push Seq cli
      run: |
        docker tag taral_seqcli:latest ghcr.io/${{ github.repository_owner }}/taral_seqcli:latest
        docker push ghcr.io/${{ github.repository_owner }}/taral_seqcli:latest
    - name: Tag and Push nginx
      run: |
        docker tag taral_nginx:latest ghcr.io/${{ github.repository_owner }}/taral_nginx:latest
        docker push ghcr.io/${{ github.repository_owner }}/taral_nginx:latest