name: Build and Push Docker images to GitHub Packages

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Frontend Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker-compose.ci.yml
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/frontend:latest
        target: frontend

    - name: Build and Push Backend Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker-compose.ci.yml
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/backend:latest
        target: backend
