name: Build and Push

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

    - name: Build images with Docker Compose
      run: docker-compose -f docker-compose.ci.yml build

    - name: Tag and Push Frontend Image
      run: |
        docker tag taral_frontend:latest ghcr.io/${{ github.repository_owner }}/taral_frontend:latest
        docker push ghcr.io/${{ github.repository_owner }}/taral_frontend:latest

    - name: Tag and Push Backend Image
      run: |
        docker tag taral_api:latest ghcr.io/${{ github.repository_owner }}/taral_api:latest
        docker push ghcr.io/${{ github.repository_owner }}/taral_api:latest
